using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ContractOne.UI.FormHelpers.SyntaxHighlight
{
    public class DatabaseKeywords
    {
        public static string[] GetKeywordsSql()
        {
            return KeywordsUpperSql.Union(KeywordsLowerSql).ToArray();
        }

        public static readonly string[] KeywordsUpperSql = { "EXEC", "EXECUTE", "EXISTS", "ADD", "ALL", "FALSE", "ALTER", "FETCH", "AND", "ANY", "FLOAT", "PRIMARY", "FOR", "AS", "FOREIGN", "ASC", "PROCEDURE", "FROM", "READ", "FULL", "AVG", "GET", "BEGIN", "GLOBAL", "BETWEEN", "GO", "BIT", "GOTO", "REVOKE", "GRANT", "RIGHT", "BOTH", "GROUP", "ROLLBACK", "BY", "HAVING", "ROWS", "CASCADE", "HOUR", "SCHEMA", "IDENTITY", "CASE", "IMMEDIATE", "SECOND", "CAST", "IN", "SECTION", "CATALOG", "SELECT", "CHAR", "INDEX", "SESSION", "INDICATOR", "SESSION_USER", "CHARACTER", "INITIALLY", "SET", "INNER", "SIZE", "CHECK", "INPUT", "SMALLINT", "CLOSE", "SOME", "COALESCE", "INSERT", "SPACE", "COLLATE", "INT", "SQL", "COLLATION", "INTEGER", "SQLCA", "COLUMN", "INTERSECT", "SQLCODE", "COMMIT", "INTERVAL", "CONNECT", "INTO", "SQLSTATE", "CONNECTION", "IS", "SQLWARNING", "CONSTRAINT", "ISOLATION", "SUBSTRING", "CONSTRAINTS", "JOIN", "SUM", "CONTINUE", "KEY", "SYSTEM_USER", "CONVERT", "LANGUAGE", "TABLE", "LAST", "TEMPORARY", "COUNT", "THEN", "CREATE", "LEFT", "TIME", "CROSS", "LEVEL", "TIMESTAMP", "CURRENT", "LIKE", "TIMEZONE_HOUR", "CURRENT_DATE", "LOCAL", "TIMEZONE_MINUTE", "CURRENT_TIME", "LOWER", "TO", "CURRENT_TIMESTAMP", "MATCH", "TRAILING", "CURRENT_USER", "MAX", "TRANSACTION", "CURSOR", "MIN", "TRANSLATE", "DATE", "MINUTE", "TRANSLATION", "DAY", "MODULE", "TRIM", "DEALLOCATE", "MONTH", "TRUE", "NAMES", "UNION", "DECIMAL", "NATIONAL", "UNIQUE", "DECLARE", "UNKNOWN", "DEFAULT", "NCHAR", "UPDATE", "DEFERRABLE", "NEXT", "UPPER", "DEFERRED", "NO", "USAGE", "DELETE", "NONE", "USER", "DESC", "NOT", "USING", "DESCRIBE", "NULL", "VALUE", "DESCRIPTOR", "NULLIF", "VALUES", "DIAGNOSTICS", "NUMERIC", "VARCHAR", "DISCONNECT", "VARYING", "DISTINCT", "OF", "VIEW", "DOMAIN", "ON", "WHEN", "DOUBLE", "ONLY", "WHENEVER", "DROP", "OPEN", "WHERE", "ELSE", "OPTION", "WITH", "END", "OR", "WORK", "END-EXEC", "ORDER", "WRITE", "ESCAPE", "OUTER", "YEAR", "EXCEPT", "OUTPUT", "ZONE", "EXCEPTION" };

        public static readonly string[] KeywordsLowerSql = { "exec", "execute", "exists", "add", "all", "false", "alter", "fetch", "and", "any", "float", "primary", "for", "as", "foreign", "asc", "procedure", "from", "read", "full", "avg", "get", "begin", "global", "between", "go", "bit", "goto", "revoke", "grant", "right", "both", "group", "rollback", "by", "having", "rows", "cascade", "hour", "schema", "identity", "case", "immediate", "second", "cast", "in", "section", "catalog", "select", "char", "index", "session", "indicator", "session_user", "character", "initially", "set", "inner", "size", "check", "input", "smallint", "close", "some", "coalesce", "insert", "space", "collate", "int", "sql", "collation", "integer", "sqlca", "column", "intersect", "sqlcode", "commit", "interval", "connect", "into", "sqlstate", "connection", "is", "sqlwarning", "constraint", "isolation", "substring", "constraints", "join", "sum", "continue", "key", "system_user", "convert", "language", "table", "last", "temporary", "count", "then", "create", "left", "time", "cross", "level", "timestamp", "current", "like", "timezone_hour", "current_date", "local", "timezone_minute", "current_time", "lower", "to", "current_timestamp", "match", "trailing", "current_user", "max", "transaction", "cursor", "min", "translate", "date", "minute", "translation", "day", "module", "trim", "deallocate", "month", "true", "names", "union", "decimal", "national", "unique", "declare", "unknown", "default", "nchar", "update", "deferrable", "next", "upper", "deferred", "no", "usage", "delete", "none", "user", "desc", "not", "using", "describe", "null", "value", "descriptor", "nullif", "values", "diagnostics", "numeric", "varchar", "disconnect", "varying", "distinct", "of", "view", "domain", "on", "when", "double", "only", "whenever", "drop", "open", "where", "else", "option", "with", "end", "or", "work", "end-exec", "order", "write", "escape", "outer", "year", "except", "output", "zone", "exception" };
    }
}
